# CHANGE NAME!
name: base_flutter_project
description: A new Flutter project

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  hydrated_bloc: ^9.1.0
  equatable: ^2.0.3
  path_provider: ^2.0.10
  flutter_displaymode: ^0.5.0
  hive: ^2.2.1
  ionicons: ^0.2.1
  intl: ^0.18.0
  http: ^0.13.4
  logger: ^1.1.0

  # run : flutter pub run flutter_native_splash:create --path=<Project Path>/flutter_native_splash.yaml
  flutter_native_splash: ^2.2.4
  flutter_launcher_icons: ^0.12.0
  json_serializable: ^6.3.1
  json_annotation: ^4.0.0-nullsafety.0
  dartz: ^0.10.1
  shared_preferences: ^2.0.15
  animations: ^2.0.3
  shimmer: ^2.0.0
  expandable: ^5.0.1
  pin_code_fields: ^7.4.0
  dropdown_search: ^5.0.2
  carousel_slider: ^4.1.1
  package_info_plus: ^3.0.3
  package_info_plus_web: ^2.0.0
  flutter_svg: ^1.1.5
  syncfusion_flutter_datepicker: ^20.3.49
  syncfusion_flutter_gauges: ^20.4.44
  tutorial_coach_mark: ^1.2.4
  collection: ^1.17.1
  local_auth: ^2.1.3
  notification_permissions: ^0.6.1
  flutter_dotenv: ^5.0.2
  permission_handler: ^10.2.0
  open_filex: ^4.3.2
  photo_view: ^0.14.0

  # FIREBASE
  firebase_analytics: ^10.1.6
  firebase_core: ^2.8.0
  firebase_messaging: ^14.3.0
  flutter_local_notifications: ^13.0.0
  cloud_firestore: ^4.4.5

dev_dependencies:
  flutter_lints: ^2.0.1
  build_runner: ^2.0.0

# run : 'flutter pub run flutter_launcher_icons:main' to update app icons
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/app-icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  # uses-material-design: false

  assets:
    - assets/images/app-icon.png
    - develop.env
    - staging.env
    - production.env

  fonts:
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/montserrat_regular.ttf
          weight: 500

    - family: MontserratSemiBold
      fonts:
        - asset: assets/fonts/montserrat_medium.ttf
          weight: 700

    - family: MontserratBold
      fonts:
        - asset: assets/fonts/montserrat_extraBold.ttf
          weight: 700

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
